theme: null
title: DG4EST Documentation
description: Your project description goes here.
baseurl: "" # leave empty unless your site is at a subpath
url: "https://dg4est.github.io" # update with your GitHub Pages URL

collections:
  docs:
    output: true

defaults:
  - scope:
      path: ""
      type: "docs"
    values:
      layout: default