name: build

on:
  push:
    branches:
      - main

jobs:
  buildpages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Install Jekyll
        run: gem install jekyll

      - name: Build
        run: jekyll build  # Generates site into _site/ by default

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          BRANCH: gh-pages
          FOLDER: _site
          CLEAN: true
# SIMPLILIFIED WORKFLOW FOR JEKYLL