name: build

on:
  push:
    branches:
      - main

jobs:
  buildpages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'  # Change as needed

      - name: Install Jekyll and dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build the site with Jekyll
        run: |
          bundle exec jekyll build
          touch _site/.nojekyll
          ls -altr _site

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          BRANCH: gh-pages
          FOLDER: _site        # Use Jekyll's output folder
          CLEAN: false         # Automatically remove deleted files? Set to true if desired.
          TARGET-FOLDER: docs   # If you want to deploy to a subdirectory
